// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/upload" | "/profile" | "/*";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/login": typeof import("./app/routes/login.js");
  "routes/dashboard": typeof import("./app/routes/dashboard.js");
  "routes/upload": typeof import("./app/routes/upload.js");
  "routes/profile": typeof import("./app/routes/profile.js");
  "routes/not-found": typeof import("./app/routes/not-found.js");
};